# =============================
# ConfigMap - Statik HTML
# =============================
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-html
  namespace: sample-app
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="tr">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Huawei Cloud | Sercan Onbaşı</title>
      <script src="https://cdn.tailwindcss.com"></script>
      <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                huawei: '#C7000B',
                huaweiLight: '#E60012'
              }
            }
          }
        }
      </script>
      <style>
        html { scroll-behavior: smooth; }
      </style>
    </head>
    <body class="bg-slate-950 text-slate-100">

      <!-- Navbar -->
      <header class="sticky top-0 z-50 bg-slate-950/90 backdrop-blur border-b border-slate-800">
        <div class="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <h1 class="text-xl font-bold text-huawei">Huawei Cloud</h1>
          <nav class="space-x-6 text-sm">
            <a href="#about" class="hover:text-huaweiLight">GitOps</a>
            <a href="#architecture" class="hover:text-huaweiLight">Mimari</a>
            <a href="#deploy" class="hover:text-huaweiLight">Deploy</a>
          </nav>
        </div>
      </header>

      <!-- Hero -->
      <section class="relative overflow-hidden">
        <div class="absolute inset-0 bg-gradient-to-br from-huawei/30 via-red-900/10 to-slate-900"></div>
        <div class="relative max-w-7xl mx-auto px-6 py-32 text-center">
          <h2 class="text-5xl font-extrabold tracking-tight mb-6">
            GitOps ile <span class="text-huawei">Otomatik</span> Deployment
          </h2>
          <p class="max-w-2xl mx-auto text-slate-300 text-lg mb-10">
            Huawei Cloud üzerinde ArgoCD kullanılarak Git üzerinden otomatik Kubernetes deployment.
          </p>
        </div>
      </section>

      <!-- About -->
      <section id="about" class="max-w-7xl mx-auto px-6 py-24">
        <h3 class="text-3xl font-bold mb-4 text-huawei">GitOps Nedir?</h3>
        <p class="text-slate-300">
          GitOps, altyapı ve uygulama konfigürasyonlarının tek doğruluk kaynağı olarak Git repository'lerini kullanan modern bir yaklaşımdır.
        </p>
      </section>

      <!-- Footer -->
      <footer class="border-t border-slate-800 bg-slate-950">
        <div class="max-w-7xl mx-auto px-6 py-8 text-center text-sm text-slate-500">
          Huawei Cloud • ArgoCD • Kubernetes • GitOps
        </div>
      </footer>

    </body>
    </html>
---
# =============================
# Deployment
# =============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web
  namespace: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: demo-html
---
# =============================
# Service
# =============================
apiVersion: v1
kind: Service
metadata:
  name: static-web
  namespace: sample-app
spec:
  selector:
    app: static-web
  ports:
    - port: 81
      targetPort: 80
